apiVersion: apps/v1
kind: Deployment
metadata:
  name: ug-feed
  labels:
    app: ug-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ug-feed
  template:
    metadata:
      labels:
        app: ug-feed
    spec:
      containers:
      - name: ug-feed 
        image: alexm1297/ug-feed:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 64Mi
          limits:
            memory: 1024Mi  
        livenessProbe:
            httpGet:
              path: /api/v0/feed
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3      
        env:
        - name: URL #actually a port
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: URL #actually a port
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: JWT_SECRET
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: AWS_PROFILE
        - name: AWS_BUCKET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: AWS_BUCKET
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ug-feed
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ug-feed 
  type: NodePort